source ~/dotfiles/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle ssh-agent
antigen bundle pass
antigen bundle virtualenvwrapper

#antigen bundle zsh-users/zsh-autosuggestions # Slows down the terminal :(
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle hlissner/zsh-autopair

antigen theme simple

antigen apply

. /usr/share/autojump/autojump.zsh

# Go
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export VISUAL=vim
export EDITOR=vim
export TERMINAL=urxvtc
export BROWSER=google-chrome

# Python
export PIP_REQUIRE_VIRTUALENV=true
export VIRTUALENV_PYTHON=python3
export WORKON_HOME=~/.virtualenvs
