call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-markdown'
Plug 'tpope/vim-commentary'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'rking/ag.vim'
Plug 'pbrisbin/vim-colors-off'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'SirVer/ultisnips'
Plug 'ervandew/supertab'
Plug 'jiangmiao/auto-pairs'
Plug 'fatih/vim-go'
Plug 'Chiel92/vim-autoformat'
Plug 'nvie/vim-flake8'

Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'marijnh/tern_for_vim'
Plug 'Valloric/YouCompleteMe'
Plug 'elzr/vim-json', {'for' : 'json'}
Plug 'ekalinin/Dockerfile.vim', {'for' : 'Dockerfile'}

call plug#end()

set nocompatible
filetype off
filetype plugin indent on

set ttyfast
set ttymouse=xterm2
set ttyscroll=3

set encoding=utf-8              " Set default encoding to UTF-8
set autoread                    " Automatically reread changed files without asking me anything
set autoindent                  
set backspace=indent,eol,start  " Makes backspace key more powerful.
set incsearch                   " Shows the match while typing

" COLORS
" ------------------------------------------------------------------------------

syntax enable
set t_Co=256

set background=dark
colorscheme off

" SETTINGS
" ------------------------------------------------------------------------------

set noswapfile	   " Disable swap files.
set nobackup       " Don't create backups.
set nocursorcolumn " do not highlight column
set nocursorline   " do not highlight line
set nowrap    	   " Do not wrap long lines.

set re=1           " use old regex engine, faster for Go highlighting
set number         " Display line numbers
set hidden    	   " Hide buffers
set lazyredraw     " Disable excessive redrawing.
set scrolloff=5    " Keep lines above and below the cursor when scrolling.
set sidescroll=1
set fillchars=""   " Remove the vertical split separator.
set breakindent    " keep wrapped lines indented
set splitright               " Split vertical windows right to the current windows
set splitbelow               " Split horizontal windows below to the current windows

set history=1000
set linespace=0

set ignorecase     " Ignore case when searching.
set smartcase      " Only ignore case when search string is lowercase.
set nohlsearch     " Don't highlight matches

set completeopt-=preview " Disable preview window on autocomplete

set tabstop=4
set shiftwidth=4
set softtabstop=4

set laststatus=1
set wildmenu       " Visual auto-complete for command menu
set mouse=a        " Enable mouse support
set pumheight=10             " Completion window max size

" These remove Esc delay
set ttimeout
set ttimeoutlen=50

" MAPPINGS
" ------------------------------------------------------------------------------

let mapleader=","

" Remap H and L (top, bottom of screen to left and right end of line)
nnoremap H ^
nnoremap L $
vnoremap H ^
vnoremap L g_

" Visual linewise up and down by default
noremap j gj
noremap k gk

" Have the indent commands re-highlight the last visual selection to make
" multiple indentations easier
vnoremap > >gv
vnoremap < <gv

let loaded_matchparen = 1 
let g:netrw_banner=0 

" Switch between last two buffers
nnoremap <leader><leader> <C-^>

" System clipboard
nnoremap <Leader>p "+]p
nnoremap <Leader>P "+]P
vnoremap <Leader>y "+y
vnoremap <Leader>d "+d

map <leader>n :NERDTreeToggle<cr>

" Learn Vim!
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" COMPLETION
" ------------------------------------------------------------------------------

let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']

" make YCM compatible with UltiSnips (using supertab)
let g:SuperTabDefaultCompletionType = '<C-n>'

" PLUGINS
" ------------------------------------------------------------------------------

" Markdown
autocmd BufRead,BufNewFile *.md,*.mkd,*.markdown setlocal spell 

" Go programming
au FileType go nmap <leader>b :GoBuild<CR>
au FileType go nmap <leader>c :GoCoverageToggle<CR>
au FileType go nmap <leader>d :GoDoc<CR>
au FileType go nmap <leader>t :GoTest<CR>

let g:go_fmt_command="goimports"

" Toggle between test and implementation
nmap T :GoAlternate<CR>

" UltiSnips
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

" CtrlP
let g:ctrlp_working_path_mode = 'ra'

nmap <C-b> :CtrlPBuffer<CR>

autocmd BufWrite *.ngt :Autoformat
autocmd BufWrite *.html :Autoformat
autocmd BufWrite *.css :Autoformat
autocmd BufWrite *.js :Autoformat
autocmd BufWrite *.py :Autoformat

" Ag
let g:ctrlp_user_command = 'ag %s -l --nocolor --hidden -g ""'

" Shell
au BufRead,BufNewFile *.sh set makeprg=shellcheck\ -f\ gcc\ %
au BufWritePost *.sh :silent make | redraw!
au QuickFixCmdPost [^l]* nested cwindow
au QuickFixCmdPost    l* nested lwindow
