#!/bin/bash

export PATH=$HOME/dotfiles/bin:$PATH

# load default settings
xrdb -load $HOME/.Xdefaults

# configure keyboard
xset r rate 200 40

# trackpad
synclient TapButton1=1
synclient TapButton2=3
synclient TapButton3=2
synclient VertTwoFingerScroll=1
synclient HorizTwoFingerScroll=1
synclient VertScrollDelta=-114
synclient HorizScrollDelta=-114

# applets
pasystray &
nm-applet &
udiskie --smart-tray &

# lock screen daemon
light-locker &

# start terminal daemon
urxvtd -q -o -f

compton -b
